# Generated by Django 4.2.1 on 2023-05-10 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 11, 1, 25, 164734, tzinfo=datetime.timezone.utc)),
        ),
    ]
