# Generated by Django 4.2.1 on 2023-05-10 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 11, 11, 55, 376880, tzinfo=datetime.timezone.utc)),
        ),
    ]
