# Generated by Django 4.2.1 on 2023-05-10 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 11, 16, 37, 277941, tzinfo=datetime.timezone.utc)),
        ),
    ]
